# Generated by Django 4.0.6 on 2022-07-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='untitled<built-in function id>', max_length=200, null=True),
        ),
    ]
